In [90]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [131]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [92]:
def derivative_sigmoid(x):
    return x*(1-x)

In [93]:
def mean_squared_error(yact,ypred):
    return np.mean((yact-ypred)**2)

In [139]:
#inputs and outputs
input = np.array([[1,0]])
output = np.array([[1]])

In [112]:
#input, hidden and output sizes
input_size = 2
hidden_size = 2
output_size = 1

In [113]:
np.random.seed(42)

In [114]:
w1 = np.array([[0.1,0.2],[0.3,0.4]])
b1= np.array([[0.1],[0.2]])
w2 = np.array([[0.5],[0.6]])
b2 = np.array([0.3])
lr = 0.1
print("\nw1 is\n", w1)
print("\nb1 is\n", b1)
print("\nw2 is\n", w2)
print("\nb2 is\n", b2)


w1 is
 [[0.1 0.2]
 [0.3 0.4]]

b1 is
 [[0.1]
 [0.2]]

w2 is
 [[0.5]
 [0.6]]

b2 is
 [0.3]


In [115]:
#initialize weights
#w2 = np.random.randn(hidden_size, output_size)
#b2 = np.random.randn(output_size)

#w1 = np.random.randn(input_size, hidden_size)
#b1 = np.random.randn(hidden_size)

In [140]:
a1 = np.dot(w1, input.T) + b1
h1 = sigmoid(a1)

print("a1 is\n", a1)
print("\nh1 is\n", h1)

a2 = np.dot(w2.T, h1) + b2
h2 = np.array(sigmoid(a2))

print("\na2 is\n", a2)
print("\nh2 is\n", h2)

error = h2 - output

loss = mean_squared_error(output, h2)


print("\nerror is\n", error)
print("\nloss is\n", loss)


gradient2 = error*derivative_sigmoid(h2)
error_hidden = gradient2.dot(w2.T)
gradient1 = error_hidden * derivative_sigmoid(h1)



print("\ngradient2 is\n", gradient2)
print("\ngradient1 is\n", gradient1)

a1 is
 [[0.2]
 [0.5]]

h1 is
 [[0.549834  ]
 [0.62245933]]

a2 is
 [[0.9483926]]

h2 is
 [[0.7207918]]

error is
 [[-0.2792082]]

loss is
 0.07795721810651235

gradient2 is
 [[-0.05619092]]

gradient1 is
 [[-0.00695409 -0.00834491]
 [-0.00660254 -0.00792305]]


In [144]:
w2+=lr*h1.T.dot(gradient2)
w1 += lr*input.T.dot(gradient1)

b2 += lr*np.mean(gradient2, axis = 0)
b2 += lr*np.mean(gradient1, axis = 0)

print("\nw1 is\n", w1)
print("\nb1 is\n", b1)
print("\nw2 is\n", w2)
print("\nb2 is\n", b2)

ValueError: shapes (1,2) and (1,1) not aligned: 2 (dim 1) != 1 (dim 0)

In [145]:
# Update weights
w2 += lr * h1.T.dot(gradient2)  # h1 is the activation from the previous layer
w1 += lr * input.T.dot(gradient1)  # input is the input to the network

# Update biases (correcting bias update for each layer)
b2 += lr * np.mean(gradient2, axis=0)  # Only using gradient2 to update b2
b1 += lr * np.mean(gradient1, axis=0)  # Using gradient1 to update b1

# Print updated weights and biases
print("\nw1 is\n", w1)
print("\nb1 is\n", b1)
print("\nw2 is\n", w2)
print("\nb2 is\n", b2)

ValueError: shapes (1,2) and (1,1) not aligned: 2 (dim 1) != 1 (dim 0)

In [146]:
# Update weights
w2 += lr * h1.dot(gradient2.T)  # Transpose gradient2 to align the shapes
w1 += lr * input.T.dot(gradient1)

# Update biases
b2 += lr * np.mean(gradient2, axis=0)
b1 += lr * np.mean(gradient1, axis=0)

# Print updated weights and biases
print("\nw1 is\n", w1)
print("\nb1 is\n", b1)
print("\nw2 is\n", w2)
print("\nb2 is\n", b2)


ValueError: shapes (2,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

In [153]:
# Assuming shapes of:
# input shape (N, 2) for N samples
# w1 shape (2, 2) for 2 inputs to 2 neurons
# w2 shape (2, 1) for 2 inputs to 1 output
# gradient1 shape (N, 2) if it corresponds to 2 neurons
# gradient2 shape (N, 1) if it corresponds to 1 output neuron

# Update weights
w2 += lr * h1.dot(gradient2)  # Ensure h1 is (N, 2) and gradient2 is (N, 1)
w1 += lr * input.dot(gradient1.T)  # Ensure input.T is (2, N) and gradient1 is (N, 2)
print("\nw1 is\n", w1)
print("\nb1 is\n", b1)
print("\nw2 is\n", w2)
print("\nb2 is\n", b2)
# Update biases
b2 += lr * np.mean(gradient2, axis=0)  # gradient2 should be (N, 1)
b1 += lr * np.mean(gradient1, axis=0)  # gradient1 should be (N, 2)

# Print updated weights and biases
print("\nw1 is\n", w1)
print("\nb1 is\n", b1)
print("\nw2 is\n", w2)
print("\nb2 is\n", b2)




w1 is
 [[0.09652295 0.19635026]
 [0.29652295 0.39635026]]

b1 is
 [[0.1]
 [0.2]]

w2 is
 [[0.46313287]
 [0.55986816]]

b2 is
 [0.27752363]


ValueError: non-broadcastable output operand with shape (2,1) doesn't match the broadcast shape (2,2)